import 'dart:convert';

import 'package:kader_new_flutter_app/models/all_news_response.dart';
import 'package:dio/dio.dart';


class HomeApiHelper {
  HomeApiHelper._() {
    dio = Dio();
  }
  static HomeApiHelper apiHelper = HomeApiHelper._();
  Dio dio;

  Future<List<AllNewsResponse>> getLastNews() async {
    try {
      String url = 'https://www.moh.gov.ps/test/test.php?1=1' + "&page=0";
      Response response = await dio.get(url);
      Map responses = json.decode(response.data);
      Autogenerated autogenerated = Autogenerated.fromJson(responses);
      List<AllNewsResponse> allNewsResponses =
          autogenerated.result;
      return allNewsResponses;
    } on Exception catch (e) {
      // TODO
    }
  }
  Future<List<AllNewsResponse>> getAllNews() async {
    try {
      String url = "https://www.moh.gov.ps/test/test.php?";
      // String url = 'https://www.moh.gov.ps/test/test.php?1=1';
      Response response = await dio.get(url);
      Map responses = json.decode(response.data);
      Autogenerated autogenerated = Autogenerated.fromJson(responses);
      List<AllNewsResponse> allNewsResponses =
          autogenerated.result;
      return allNewsResponses;
    } on Exception catch (e) {
      // TODO
    }
  }

  Future<List<AllNewsResponse>> getSearchNews(String word) async {
    try {
      String url = "https://www.moh.gov.ps/test/test.php?&search=$word";
      Response response = await dio.get(url);
      Map responses = json.decode(response.data);
      Autogenerated autogenerated = Autogenerated.fromJson(responses);
      List<AllNewsResponse> allNewsResponses =
          autogenerated.result;
      return allNewsResponses;
    } on Exception catch (e) {
      // TODO
    }
  }
  }

