

import 'package:kader_new_flutter_app/models/all_news_response.dart';

class Autogenerated {
  String recCount;
  List<AllNewsResponse> result;

  Autogenerated({this.recCount, this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    recCount = json['rec_count'];
    if (json['result'] != null) {
      result = <AllNewsResponse>[];
      json['result'].forEach((v) {
        result.add(AllNewsResponse.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['rec_count'] = this.recCount;
    if (this.result != null) {
      data['result'] = this.result.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
class AllNewsResponse {
  String id;
  String postDate;
  String guid;
  String postTitle;
  String postContent;
  String imageUrl;

  AllNewsResponse(
      {this.id,
        this.postDate,
        this.guid,
        this.postTitle,
        this.postContent,
        this.imageUrl});

  AllNewsResponse.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    postDate = json['post_date'];
    guid = json['guid'];
    postTitle = json['post_title'];
    postContent = json['post_content'];
    imageUrl = json['image_url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['post_date'] = this.postDate;
    data['guid'] = this.guid;
    data['post_title'] = this.postTitle;
    data['post_content'] = this.postContent;
    data['image_url'] = this.imageUrl;
    return data;
  }
}